### ISSUE TITLE
Update to storybook 8?

### ISSUE THREAD

**Issue by alecb7** [krzysztofradomski/storybook-addon-vitest#4]
Just wondering if there's any plan/timeline to make the plugin compatible with storybook 8.0+?

**Comment by krzysztofradomski** [comment]
No plan yet.  I do have some spare time in near future, so I might take a look unless someone else steps in.

**Comment by rustybud** [comment]
I just created a PR https://github.com/krzysztofradomski/storybook-addon-vitest/pull/5 for this.

**Comment by krzysztofradomski** [comment]
> I just created a PR #5 for this.
https://github.com/krzysztofradomski/storybook-addon-vitest/pull/5#pullrequestreview-2093356704

Yep, thanks!
Unfortunately, I wasn't able to run this locally. I cannot add my commit to your pr, so I made a pr against your pr with my changes. Please review them for missing setup pieces, confirm it all works locally, and update your pr here. :)
